"""Cherry-pick grounder -- attach a literature-grounded theory_citation to a
bridge-generated heavyweight Chordia DRAFT prereg.

See ``docs/specs/fast_lane_state_graph.md`` for the canonical fast-lane chain definition.

Closes the gap between fast_lane_to_heavyweight_bridge.py (which deliberately
omits theory_citation per the field-presence trap, memory/feedback_chordia_
theory_citation_field_presence_trap.md) and an active heavyweight prereg in
docs/audit/hypotheses/. Without grounding, every bridge draft sits at the
strict no-theory hurdle (t >= 3.79); successful grounding earns t >= 3.00 per
Criterion 4 (with-theory tier, Chordia 2018).

Workflow
--------
1. Read a bridge draft (docs/audit/hypotheses/drafts/*-chordia-heavyweight-v1.draft.yaml)
2. Load the local lit corpus (docs/institutional/literature/*.md) via the
   canonical lhp.literature_index.load_corpus.
3. Run search_corpus against the strategy mechanism (built from the draft's
   scope fields). If zero results: emit GROUNDED_VERDICT=NO_LOCAL_LIT and
   refuse (web fallback is operator-driven, not automated -- v1 ships without
   live web calls; trigger flag reserved for v2).
4. If results: call propose_with_mock_support to pick a citation + write a
   1-2 sentence economic_basis grounded in the top extract.
5. verify_citation_content gates the LLM output. Pass -> write <slug>.grounded.yaml
   with theory_citation + theory_grant=true. Fail -> write
   <slug>.grounded.rejected.txt and exit non-zero.

Cherry-picked (reused, not rewritten)
-------------------------------------
- scripts/research/lhp/literature_index.load_corpus, search_corpus,
  verify_citation_content, format_search_results_for_llm
- scripts/research/lhp/llm_client.propose_with_mock_support,
  CostCeilingExceeded, LLMRefusalToGround, LLMRequestError
- scripts/research/lhp/yaml_emitter.write_rejected (refusal sidecar pattern)

Doctrine grounding
------------------
- Field-presence trap defense: feedback_chordia_theory_citation_field_presence_trap.md
- LHP-validator quarantine pattern: feedback_lhp_validator_vs_field_presence_trap_n1.md
- Local-first lit grounding: institutional-rigor.md section 7 + Local Academic Grounding Rule
- Criterion 4 with-theory tier: docs/institutional/pre_registered_criteria.md
- Stage file: docs/runtime/stages/2026-05-19-cherry-pick-grounder.md

This script does NOT write to chordia_audit_log.yaml, validated_setups,
lane_allocation.json, or any file under trading_app/live/. It only writes to
docs/audit/hypotheses/drafts/<slug>.grounded.yaml (PASS) or
<slug>.grounded.rejected.txt (REFUSED). The original draft is never mutated.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

_LITERATURE_DIR = REPO_ROOT / "docs" / "institutional" / "literature"
_SYSTEM_PROMPT_PATH = REPO_ROOT / "docs" / "prompts" / "hypothesis-proposer-system.md"

from scripts.research.lhp.literature_index import (  # noqa: E402
    format_search_results_for_llm,
    load_corpus,
    search_corpus,
    verify_citation_content,
)
from scripts.research.lhp.llm_client import (  # noqa: E402
    CostCeilingExceeded,
    LLMRefusalToGround,
    LLMRequestError,
    propose_with_mock_support,
)


# Verdict labels written to <slug>.grounded.yaml (or .rejected.txt) AND
# appended to docs/runtime/cherry_pick_journal.md grounded_verdict column.
# These are the only legal values -- any new label requires a journal-schema
# update + a drift-check parity entry.
VERDICT_GROUNDED: str = "GROUNDED"
VERDICT_NO_LOCAL_LIT: str = "NO_LOCAL_LIT"
VERDICT_LLM_REFUSED: str = "LLM_REFUSED"
VERDICT_CONTENT_MISMATCH: str = "CONTENT_MISMATCH"
VERDICT_INVALID_OUTPUT: str = "INVALID_OUTPUT"

ALL_VERDICTS: tuple[str, ...] = (
    VERDICT_GROUNDED,
    VERDICT_NO_LOCAL_LIT,
    VERDICT_LLM_REFUSED,
    VERDICT_CONTENT_MISMATCH,
    VERDICT_INVALID_OUTPUT,
)


# LLM grounding system prompt. Kept inline (not in docs/prompts/) because it
# is grounder-specific and tiny. The proposer's full system prompt is loaded
# from docs/prompts/hypothesis-proposer-system.md and prepended.
GROUNDER_INSTRUCTION_TEMPLATE: str = """\
You are grounding an existing heavyweight Chordia prereg DRAFT in literature.

The DRAFT below was generated by fast_lane_to_heavyweight_bridge.py from a
fast-lane PROMOTE result. It has NO theory_citation -- that omission is
deliberate (field-presence trap defense). Your job: propose a single
theory_citation drawn ONLY from the TARGETED LITERATURE SEARCH block below,
plus a 1-2 sentence economic_basis explaining the mechanism the cited
literature attributes to this strategy class.

STRATEGY SPEC (from draft scope)
================================
{spec_block}

DRAFT EXCERPT (metadata + scope + grounding sections only)
==========================================================
{draft_excerpt}

REQUIREMENTS
============
- theory_citation MUST cite at least one slug verbatim from the search
  results below. Fabricated citations are refused at validation time.
- economic_basis MUST be 1-2 sentences describing the mechanism (e.g.,
  "stop cascade liquidity demand at the ORB break", not "this strategy
  works because the data says so").
- If NO search result plausibly grounds this strategy class, output
  exactly: REFUSE: no_literature_match
- Output ONLY a YAML block with two top-level keys: theory_citation
  and economic_basis. No commentary, no markdown fences.

OUTPUT FORMAT (exact)
=====================
theory_citation: "<slug-or-title-from-search-results>"
economic_basis: |
  <1-2 sentences citing the mechanism the literature attributes to this
  strategy class>
"""


@dataclass(frozen=True)
class GroundingResult:
    """Outcome of a grounding attempt -- one of the ALL_VERDICTS labels."""

    verdict: str
    draft_path: Path
    out_path: Path | None
    theory_citation: str | None
    economic_basis: str | None
    cited_slugs: tuple[str, ...]
    reason: str


def load_bridge_draft(draft_path: Path) -> dict[str, Any]:
    """Read a bridge draft YAML. Raises if missing or malformed."""
    if not draft_path.exists():
        raise FileNotFoundError(f"Bridge draft not found: {draft_path}")
    data = yaml.safe_load(draft_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Bridge draft is not a YAML mapping: {draft_path}")
    if "scope" not in data or not isinstance(data["scope"], dict):
        raise ValueError(
            f"Bridge draft missing scope mapping: {draft_path}. "
            "Bridge contract violated -- regenerate via "
            "scripts/research/fast_lane_to_heavyweight_bridge.py."
        )
    return data


def build_search_query(scope: dict[str, Any]) -> str:
    """Compose a corpus-search query from scope keys.

    Pulls the mechanism-bearing fields (entry_model, filter_type, session,
    direction) -- these are what the literature talks about. instrument
    and orb_minutes are descriptors, not mechanisms; they would only dilute
    the token-overlap signal.
    """
    parts: list[str] = []
    for key in ("entry_model", "filter_type", "session", "direction"):
        v = scope.get(key)
        if isinstance(v, str) and v.strip():
            parts.append(v)
    return " ".join(parts)


def format_spec_block(scope: dict[str, Any]) -> str:
    """Pretty-print the scope keys for the LLM prompt."""
    keys = (
        "strategy_id",
        "instrument",
        "session",
        "orb_minutes",
        "entry_model",
        "confirm_bars",
        "rr_target",
        "filter_type",
        "direction",
    )
    return "\n".join(
        f"  {k}: {scope[k]}" for k in keys if k in scope and scope[k] is not None
    )


def format_draft_excerpt(draft: dict[str, Any]) -> str:
    """Pull metadata + scope + grounding sections only -- keeps the LLM
    context bounded (the full bridge draft is ~80 lines of YAML)."""
    excerpt: dict[str, Any] = {}
    for key in ("metadata", "scope", "grounding"):
        if key in draft:
            excerpt[key] = draft[key]
    return yaml.safe_dump(excerpt, sort_keys=False, allow_unicode=True, width=80)


def parse_llm_grounding_output(yaml_text: str) -> dict[str, str] | None:
    """Parse the LLM's two-key YAML response.

    Returns None when the response is malformed, missing keys, or contains
    non-string values. The grounder treats parse failure as a hard refusal:
    no .grounded.yaml gets written, only .grounded.rejected.txt. This keeps
    the field-presence trap closed -- a malformed LLM output cannot leak
    an empty theory_citation into the active hypothesis tree.
    """
    text = yaml_text.strip()
    if text.startswith("```"):
        first_newline = text.find("\n")
        if first_newline != -1:
            text = text[first_newline + 1 :]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()
    if text.startswith("REFUSE:"):
        return None
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError:
        return None
    if not isinstance(parsed, dict):
        return None
    cite = parsed.get("theory_citation")
    basis = parsed.get("economic_basis")
    if not isinstance(cite, str) or not cite.strip():
        return None
    if not isinstance(basis, str) or not basis.strip():
        return None
    return {"theory_citation": cite.strip(), "economic_basis": basis.strip()}


def grounded_output_path(draft_path: Path) -> Path:
    """draft.yaml -> grounded.yaml; rejected sidecar pattern handled by write_rejected."""
    name = draft_path.name
    if name.endswith(".draft.yaml"):
        new_name = name[: -len(".draft.yaml")] + ".grounded.yaml"
    elif name.endswith(".yaml"):
        new_name = name[: -len(".yaml")] + ".grounded.yaml"
    else:
        new_name = name + ".grounded.yaml"
    return draft_path.parent / new_name


def build_grounded_draft(
    draft: dict[str, Any],
    *,
    theory_citation: str,
    economic_basis: str,
    cited_slugs: tuple[str, ...],
    query: str,
    verification: dict[str, Any],
) -> dict[str, Any]:
    """Return a copy of the bridge draft with grounding fields filled in.

    Mutations:
      - metadata.theory_grant = True (unlocks Criterion 4 t>=3.00 hurdle)
      - metadata.theory_citation = <verified citation>
      - grounding.filter_grounding_status.verdict = "LITERATURE_GROUNDED"
      - grounding.filter_grounding_status.basis = <economic_basis>
      - grounding.filter_grounding_status.cited_slugs = list
      - grounding.literature_grounding_provenance = block with query +
        verification report so future auditors can replay the decision.
      - primary_schema.chordia_threshold_basis updated to with-theory prose

    The original draft dict is NOT mutated -- a deep-copy is performed.
    """
    import copy

    grounded = copy.deepcopy(draft)
    metadata = grounded.setdefault("metadata", {})
    metadata["theory_grant"] = True
    metadata["theory_citation"] = theory_citation
    metadata["validation_status_explicit"] = (
        "LITERATURE_GROUNDED -- theory_grant=true applies Criterion 4 "
        "with-theory hurdle (t>=3.00, Chordia 2018 Tier 2). Operator must "
        "still verify era stability, OOS power, and K-budget before moving "
        "out of drafts/."
    )

    grounding = grounded.setdefault("grounding", {})
    status = grounding.setdefault("filter_grounding_status", {})
    status["verdict"] = "LITERATURE_GROUNDED"
    status["basis"] = economic_basis
    status["cited_slugs"] = list(cited_slugs)

    grounding["literature_grounding_provenance"] = {
        "source": "scripts/research/cherry_pick_grounder.py",
        "query": query,
        "verification_passes": bool(verification.get("passes")),
        "verification_reason": verification.get("reason"),
        "per_file_overlap": verification.get("per_file", []),
    }

    primary = grounded.setdefault("primary_schema", {})
    primary["chordia_threshold_basis"] = (
        "Criterion 4 with-theory threshold (t >= 3.00, Chordia 2018 Tier 2). "
        f"Citation: {theory_citation}"
    )
    primary["promotion_gate"] = (
        "PASS_CHORDIA at t>=3.00 with-theory; literature_grounding "
        "verification passes -- see grounding.literature_grounding_provenance"
    )

    return grounded


def write_grounded(grounded: dict[str, Any], out_path: Path) -> Path:
    """Write the grounded.yaml. Refuses to overwrite by default."""
    if out_path.exists():
        raise FileExistsError(
            f"Grounded draft already exists: {out_path}. Delete or rename "
            "before re-grounding."
        )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# LITERATURE-GROUNDED DRAFT -- not yet preregistered.\n"
        "# Generated by scripts/research/cherry_pick_grounder.py.\n"
        "# Operator review required before moving to docs/audit/hypotheses/:\n"
        "#   1. [ ] Read theory_citation slug + confirm economic_basis is faithful\n"
        "#   2. [ ] Verify OOS power tier via research/oos_power.py\n"
        "#   3. [ ] Verify era-stability via heavyweight replay\n"
        "#   4. [ ] Re-run K-budget gate (scripts/tools/estimate_k_budget.py)\n"
        "#   5. [ ] Move drafts/<file>.grounded.yaml -> hypotheses/<file>.yaml\n"
        "#         then flip execution_gate.allowed_now=true\n"
        "#\n"
    )
    body = yaml.safe_dump(grounded, sort_keys=False, allow_unicode=True, width=80)
    out_path.write_text(header + body, encoding="utf-8")
    return out_path


def write_grounded_rejected(
    draft_path: Path,
    verdict: str,
    reason: str,
    *,
    raw_llm_output: str = "",
) -> Path:
    """Write the .grounded.rejected.txt sidecar."""
    out = grounded_output_path(draft_path).with_suffix(".rejected.txt")
    body = (
        f"# REJECTED GROUNDING -- verdict={verdict}\n"
        f"# Source draft: {draft_path.name}\n"
        f"# Reason: {reason}\n"
        "#\n"
        "# This file is NOT a valid hypothesis. Do not rename to .yaml.\n"
        "# Original bridge draft is unchanged -- operator may regenerate\n"
        "# with --ground after either (a) adding the missing lit extract,\n"
        "# (b) revising the LLM prompt, or (c) accepting the no-theory\n"
        "# strict 3.79 hurdle and moving the bridge draft directly.\n"
        "#\n"
    )
    if raw_llm_output:
        body += "# Raw LLM output (for audit):\n"
        for line in raw_llm_output.splitlines():
            body += f"#   {line}\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    return out


def ground_bridge_draft(
    draft_path: Path,
    *,
    literature_dir: Path = _LITERATURE_DIR,
    top_k: int = 5,
    cost_ceiling_usd: float = 0.50,
    model: str | None = None,
    system_prompt: str | None = None,
) -> GroundingResult:
    """Run the full grounding pipeline against a bridge draft.

    Returns a GroundingResult describing the outcome. On VERDICT_GROUNDED the
    out_path is the path to the newly written .grounded.yaml. On any refusal
    verdict the out_path is the .grounded.rejected.txt sidecar.
    """
    draft = load_bridge_draft(draft_path)
    scope = draft["scope"]
    query = build_search_query(scope)

    corpus = load_corpus(literature_dir)
    results = search_corpus(corpus, query, top_k=top_k)

    if not results:
        rej = write_grounded_rejected(
            draft_path,
            VERDICT_NO_LOCAL_LIT,
            (
                "search_corpus returned zero extracts above min_overlap=2 "
                f"for query={query!r}. Local-first grounding refuses; web "
                "fallback is operator-driven (v1 ships without automated "
                "web fetches -- author a lit extract under "
                "docs/institutional/literature/ and retry)."
            ),
        )
        return GroundingResult(
            verdict=VERDICT_NO_LOCAL_LIT,
            draft_path=draft_path,
            out_path=rej,
            theory_citation=None,
            economic_basis=None,
            cited_slugs=(),
            reason="no local literature match",
        )

    spec_block = format_spec_block(scope)
    excerpt = format_draft_excerpt(draft)
    search_block = format_search_results_for_llm(results)
    user_instruction = GROUNDER_INSTRUCTION_TEMPLATE.format(
        spec_block=spec_block,
        draft_excerpt=excerpt,
    )

    sys_prompt = system_prompt
    if sys_prompt is None and _SYSTEM_PROMPT_PATH.is_file():
        sys_prompt = _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8")
    if sys_prompt is None:
        sys_prompt = "You are a hypothesis-grounding assistant."

    try:
        result = propose_with_mock_support(
            system_prompt=sys_prompt,
            fewshot="",
            corpus_summary="",
            adjacency_context=search_block,
            user_instruction=user_instruction,
            cost_ceiling_usd=cost_ceiling_usd,
            model=model,
        )
    except LLMRefusalToGround as exc:
        rej = write_grounded_rejected(
            draft_path,
            VERDICT_LLM_REFUSED,
            f"LLM emitted refusal sentinel: {exc}",
        )
        return GroundingResult(
            verdict=VERDICT_LLM_REFUSED,
            draft_path=draft_path,
            out_path=rej,
            theory_citation=None,
            economic_basis=None,
            cited_slugs=(),
            reason=str(exc),
        )
    except (CostCeilingExceeded, LLMRequestError) as exc:
        raise RuntimeError(
            f"Grounder LLM call failed: {exc}. Bridge draft is untouched; "
            "rerun after fixing the LLM access path."
        ) from exc

    parsed = parse_llm_grounding_output(result.yaml_text)
    if parsed is None:
        rej = write_grounded_rejected(
            draft_path,
            VERDICT_INVALID_OUTPUT,
            (
                "LLM output failed to parse as the expected two-key YAML "
                "{theory_citation, economic_basis} OR contained empty values. "
                "Field-presence trap defense: empty theory_citation is "
                "NEVER written to a grounded draft."
            ),
            raw_llm_output=result.yaml_text,
        )
        return GroundingResult(
            verdict=VERDICT_INVALID_OUTPUT,
            draft_path=draft_path,
            out_path=rej,
            theory_citation=None,
            economic_basis=None,
            cited_slugs=(),
            reason="malformed LLM output",
        )

    theory_citation = parsed["theory_citation"]
    economic_basis = parsed["economic_basis"]

    verification = verify_citation_content(
        corpus, theory_citation, economic_basis
    )
    cited_files_raw = verification.get("cited_files", [])
    cited_files: list[str] = []
    if isinstance(cited_files_raw, (list, tuple)):
        for entry in cited_files_raw:  # type: ignore[reportUnknownVariableType]
            cited_files.append(str(entry))

    if not verification["passes"]:
        rej = write_grounded_rejected(
            draft_path,
            VERDICT_CONTENT_MISMATCH,
            f"verify_citation_content failed: {verification['reason']}",
            raw_llm_output=result.yaml_text,
        )
        return GroundingResult(
            verdict=VERDICT_CONTENT_MISMATCH,
            draft_path=draft_path,
            out_path=rej,
            theory_citation=theory_citation,
            economic_basis=economic_basis,
            cited_slugs=tuple(cited_files),
            reason=str(verification["reason"]),
        )

    cited_slugs = tuple(cited_files)
    grounded = build_grounded_draft(
        draft,
        theory_citation=theory_citation,
        economic_basis=economic_basis,
        cited_slugs=cited_slugs,
        query=query,
        verification=verification,
    )
    out_path = grounded_output_path(draft_path)
    write_grounded(grounded, out_path)
    return GroundingResult(
        verdict=VERDICT_GROUNDED,
        draft_path=draft_path,
        out_path=out_path,
        theory_citation=theory_citation,
        economic_basis=economic_basis,
        cited_slugs=cited_slugs,
        reason="literature_grounding_OK",
    )


def format_operator_message(result: GroundingResult) -> str:
    """Human-facing summary printed after ground_bridge_draft returns."""
    if result.out_path is None:
        rel = "(no output written)"
    else:
        try:
            rel = str(result.out_path.relative_to(REPO_ROOT))
        except ValueError:
            rel = str(result.out_path)
    if result.verdict == VERDICT_GROUNDED:
        return (
            f"\nGROUNDED: {rel}\n"
            f"  citation: {result.theory_citation}\n"
            f"  cited_slugs: {list(result.cited_slugs)}\n"
            "\n"
            "Operator next steps:\n"
            "  1. Read the grounded.yaml + confirm citation matches mechanism\n"
            "  2. Verify OOS power tier via research/oos_power.py\n"
            "  3. Re-run K-budget gate before moving to hypotheses/\n"
            "  4. Append grounded_verdict=GROUNDED row to "
            "docs/runtime/cherry_pick_journal.md\n"
        )
    return (
        f"\nREFUSED ({result.verdict}): {rel}\n"
        f"  reason: {result.reason}\n"
        "\n"
        "Original bridge draft is unchanged. Either:\n"
        "  (a) Author the missing literature extract under "
        "docs/institutional/literature/ then retry\n"
        "  (b) Accept the no-theory strict 3.79 hurdle and move the bridge "
        "draft directly\n"
        "  (c) Append grounded_verdict=" + result.verdict + " row to "
        "docs/runtime/cherry_pick_journal.md\n"
    )


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="cherry_pick_grounder",
        description=(
            "Attach a literature-grounded theory_citation to a bridge-generated "
            "heavyweight Chordia DRAFT prereg. Writes <slug>.grounded.yaml on "
            "PASS or <slug>.grounded.rejected.txt on REFUSED. Never mutates "
            "the original bridge draft."
        ),
    )
    p.add_argument(
        "draft",
        type=Path,
        help=(
            "Path to a bridge draft, "
            "docs/audit/hypotheses/drafts/*-chordia-heavyweight-v1.draft.yaml."
        ),
    )
    p.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Top-K extracts to surface to the LLM (default 5).",
    )
    p.add_argument(
        "--cost-ceiling",
        type=float,
        default=0.50,
        help="USD cost ceiling per LLM call (default 0.50).",
    )
    p.add_argument(
        "--model",
        type=str,
        default=None,
        help="LLM model id. Defaults to canonical CLAUDE_REASONING_MODEL.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    try:
        result = ground_bridge_draft(
            args.draft,
            top_k=args.top_k,
            cost_ceiling_usd=args.cost_ceiling,
            model=args.model,
        )
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 5
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 5
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 3
    print(format_operator_message(result))
    return 0 if result.verdict == VERDICT_GROUNDED else 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
